"""empty message

Revision ID: cc06564b6efe
Revises: 
Create Date: 2019-09-13 23:32:57.932206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc06564b6efe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('things',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('things')
    # ### end Alembic commands ###
